# .bashrc

# set up some generic CVS stuff
#CVSROOT=cvs:/cvs
CVS_RSH=ssh
export CVSROOT CVS_RSH

# load system wide defs
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# set my editor
export EDITOR=vim 

# and me path
PATH=$PATH:$HOME/bin:/opt/local/bin:/opt/local/Library/Frameworks/Python.framework/Versions/2.6/bin:$HOME/android/sdk-r06/tools

export math=/usr/local/Wolfram/Mathematica

# give me a cool prompt
PS1="\[[00;33m\]$((SHLVL-1)) \[[00;32m\]\h\[[00;39m\] | \[[00;34m\]\W\[[00;39m\] \$ "
export PS1 

## DJANGO
#export LL_DJANGO_MODE=local

[ -f /opt/local/etc/bash_completion ] && . /opt/local/etc/bash_completion

export GPG_TTY=`tty`

agent_running=$(ps -u $USER | grep gpg-agent | grep -v grep)

if [ -z "$agent_running" ]; then
    eval $(gpg-agent --daemon --write-env-file=$HOME/.gpg_agent_info)
    # figure out how this plays with current ssh-agent
    #export SSH_AUTH_SOCK
else
    . $HOME/.gpg_agent_info
fi
export GPG_AGENT_INFO

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi
