# .bashrc
if [ -e ~/.bash_path ]; then
    . ~/.bash_path
    for d in $path; do 
        if [ -d "$d" -a -z "$(echo $PATH | grep "$d" 2>/dev/null)" ]; then
            PATH=$d:$PATH
        fi
    done
    export PATH
fi


# load system wide defs
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# set my editor
export EDITOR=vim
export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWUNTRACKEDFILES=1
export GIT_PS1_SHOWUPSTREAM="auto git"


[ -f /opt/local/etc/bash_completion ] && . /opt/local/etc/bash_completion

# give me a cool prompt
PS1='\[[00;32m\]\u\[[00;39m\]@\[[00;32m\]\h\[[00;39m\]:\[[00;34m\]\W\[[00;39m\] $(__git_ps1 "(%s)")\$ '
export PS1 

export GPG_TTY=`tty`

function ip() { 
  iface=${1:-en1}
  /sbin/ifconfig $iface | sed -E '/inet /s/^.*inet ([\.0-9]+).*/\1/p;d'
}

# empty stubs
function solarize() {
    :
}

function desolarize() {
    :
}

agent_running=$(ps -u $USER | grep gpg-agent | grep -v grep)

if [ -z "$agent_running" ]; then
    eval $(gpg-agent --daemon --write-env-file=$HOME/.gpg_agent_info)
    # figure out how this plays with current ssh-agent
    #export SSH_AUTH_SOCK
else
    . $HOME/.gpg_agent_info
fi
export GPG_AGENT_INFO

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

#PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

#[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

eval "$(rbenv init -)"
